<?php

/**
 * TransactionStatus.
 *
 * PHP version 8.3
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).
 *
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * The version of the OpenAPI document: 2024-03-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SpApi\Model\sellerWallet\v2024_03_01;

/**
 * TransactionStatus Class Doc Comment.
 *
 * @category Class
 *
 * @description Represents current status of the transaction.
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
class TransactionStatus
{
    /**
     * Possible values of this enum.
     */
    public const EXPIRED = 'EXPIRED';

    public const FAILED = 'FAILED';

    public const FAILED_CREDITS_APPLIED = 'FAILED_CREDITS_APPLIED';

    public const IN_PROGRESS = 'IN_PROGRESS';

    public const PENDING_USER_APPROVAL = 'PENDING_USER_APPROVAL';

    public const SUCCESSFUL = 'SUCCESSFUL';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues(): array
    {
        return [
            self::EXPIRED,
            self::FAILED,
            self::FAILED_CREDITS_APPLIED,
            self::IN_PROGRESS,
            self::PENDING_USER_APPROVAL,
            self::SUCCESSFUL,
        ];
    }
}
