<?php

/**
 * Order.
 *
 * PHP version 8.3
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Orders.
 *
 * The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SpApi\Model\orders\v2026_01_01;

use SpApi\Model\ModelInterface;
use SpApi\ObjectSerializer;

/**
 * Order Class Doc Comment.
 *
 * @category Class
 *
 * @description Comprehensive information about a customer order.
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class Order implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     */
    protected static string $openAPIModelName = 'Order';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static array $openAPITypes = [
        'order_id' => 'string',
        'order_aliases' => '\SpApi\Model\orders\v2026_01_01\Alias[]',
        'created_time' => '\DateTime',
        'last_updated_time' => '\DateTime',
        'programs' => 'string[]',
        'associated_orders' => '\SpApi\Model\orders\v2026_01_01\AssociatedOrder[]',
        'sales_channel' => '\SpApi\Model\orders\v2026_01_01\SalesChannel',
        'buyer' => '\SpApi\Model\orders\v2026_01_01\Buyer',
        'recipient' => '\SpApi\Model\orders\v2026_01_01\Recipient',
        'proceeds' => '\SpApi\Model\orders\v2026_01_01\OrderProceeds',
        'fulfillment' => '\SpApi\Model\orders\v2026_01_01\OrderFulfillment',
        'order_items' => '\SpApi\Model\orders\v2026_01_01\OrderItem[]',
        'packages' => '\SpApi\Model\orders\v2026_01_01\OrderPackage[]'];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'order_id' => null,
        'order_aliases' => null,
        'created_time' => 'date-time',
        'last_updated_time' => 'date-time',
        'programs' => null,
        'associated_orders' => null,
        'sales_channel' => null,
        'buyer' => null,
        'recipient' => null,
        'proceeds' => null,
        'fulfillment' => null,
        'order_items' => null,
        'packages' => null];

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'order_id' => false,
        'order_aliases' => true,
        'created_time' => false,
        'last_updated_time' => false,
        'programs' => true,
        'associated_orders' => true,
        'sales_channel' => false,
        'buyer' => true,
        'recipient' => true,
        'proceeds' => true,
        'fulfillment' => true,
        'order_items' => false,
        'packages' => true,
    ];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'order_id' => 'orderId',
        'order_aliases' => 'orderAliases',
        'created_time' => 'createdTime',
        'last_updated_time' => 'lastUpdatedTime',
        'programs' => 'programs',
        'associated_orders' => 'associatedOrders',
        'sales_channel' => 'salesChannel',
        'buyer' => 'buyer',
        'recipient' => 'recipient',
        'proceeds' => 'proceeds',
        'fulfillment' => 'fulfillment',
        'order_items' => 'orderItems',
        'packages' => 'packages',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static array $setters = [
        'order_id' => 'setOrderId',
        'order_aliases' => 'setOrderAliases',
        'created_time' => 'setCreatedTime',
        'last_updated_time' => 'setLastUpdatedTime',
        'programs' => 'setPrograms',
        'associated_orders' => 'setAssociatedOrders',
        'sales_channel' => 'setSalesChannel',
        'buyer' => 'setBuyer',
        'recipient' => 'setRecipient',
        'proceeds' => 'setProceeds',
        'fulfillment' => 'setFulfillment',
        'order_items' => 'setOrderItems',
        'packages' => 'setPackages',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static array $getters = [
        'order_id' => 'getOrderId',
        'order_aliases' => 'getOrderAliases',
        'created_time' => 'getCreatedTime',
        'last_updated_time' => 'getLastUpdatedTime',
        'programs' => 'getPrograms',
        'associated_orders' => 'getAssociatedOrders',
        'sales_channel' => 'getSalesChannel',
        'buyer' => 'getBuyer',
        'recipient' => 'getRecipient',
        'proceeds' => 'getProceeds',
        'fulfillment' => 'getFulfillment',
        'order_items' => 'getOrderItems',
        'packages' => 'getPackages',
    ];

    /**
     * Associative array for storing property values.
     */
    protected array $container = [];

    /**
     * Constructor.
     *
     * @param null|array $data Associated array of property values
     *                         initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('order_id', $data ?? [], null);
        $this->setIfExists('order_aliases', $data ?? [], null);
        $this->setIfExists('created_time', $data ?? [], null);
        $this->setIfExists('last_updated_time', $data ?? [], null);
        $this->setIfExists('programs', $data ?? [], null);
        $this->setIfExists('associated_orders', $data ?? [], null);
        $this->setIfExists('sales_channel', $data ?? [], null);
        $this->setIfExists('buyer', $data ?? [], null);
        $this->setIfExists('recipient', $data ?? [], null);
        $this->setIfExists('proceeds', $data ?? [], null);
        $this->setIfExists('fulfillment', $data ?? [], null);
        $this->setIfExists('order_items', $data ?? [], null);
        $this->setIfExists('packages', $data ?? [], null);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Checks if a property is nullable.
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (null === $this->container['order_id']) {
            $invalidProperties[] = "'order_id' can't be null";
        }
        if (null === $this->container['created_time']) {
            $invalidProperties[] = "'created_time' can't be null";
        }
        if (null === $this->container['last_updated_time']) {
            $invalidProperties[] = "'last_updated_time' can't be null";
        }
        if (null === $this->container['sales_channel']) {
            $invalidProperties[] = "'sales_channel' can't be null";
        }
        if (null === $this->container['order_items']) {
            $invalidProperties[] = "'order_items' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets order_id.
     */
    public function getOrderId(): string
    {
        return $this->container['order_id'];
    }

    /**
     * Sets order_id.
     *
     * @param string $order_id an Amazon-defined order identifier
     */
    public function setOrderId(string $order_id): self
    {
        if (is_null($order_id)) {
            throw new \InvalidArgumentException('non-nullable order_id cannot be null');
        }
        $this->container['order_id'] = $order_id;

        return $this;
    }

    /**
     * Gets order_aliases.
     */
    public function getOrderAliases(): ?array
    {
        return $this->container['order_aliases'];
    }

    /**
     * Sets order_aliases.
     *
     * @param null|array $order_aliases alternative identifiers that can be used to reference this order, such as seller-defined order numbers
     */
    public function setOrderAliases(?array $order_aliases): self
    {
        if (is_null($order_aliases)) {
            array_push($this->openAPINullablesSetToNull, 'order_aliases');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('order_aliases', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['order_aliases'] = $order_aliases;

        return $this;
    }

    /**
     * Gets created_time.
     */
    public function getCreatedTime(): \DateTime
    {
        return $this->container['created_time'];
    }

    /**
     * Sets created_time.
     *
     * @param \DateTime $created_time The time when the customer placed the order. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     */
    public function setCreatedTime(\DateTime $created_time): self
    {
        if (is_null($created_time)) {
            throw new \InvalidArgumentException('non-nullable created_time cannot be null');
        }
        $this->container['created_time'] = $created_time;

        return $this;
    }

    /**
     * Gets last_updated_time.
     */
    public function getLastUpdatedTime(): \DateTime
    {
        return $this->container['last_updated_time'];
    }

    /**
     * Sets last_updated_time.
     *
     * @param \DateTime $last_updated_time The most recent time when any aspect of this order was modified by Amazon or the seller. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     */
    public function setLastUpdatedTime(\DateTime $last_updated_time): self
    {
        if (is_null($last_updated_time)) {
            throw new \InvalidArgumentException('non-nullable last_updated_time cannot be null');
        }
        $this->container['last_updated_time'] = $last_updated_time;

        return $this;
    }

    /**
     * Gets programs.
     */
    public function getPrograms(): ?array
    {
        return $this->container['programs'];
    }

    /**
     * Sets programs.
     *
     * @param null|array $programs Special programs associated with this order that may affect fulfillment or customer experience.   **Possible values**: `AMAZON_BAZAAR`, `AMAZON_BUSINESS`,  `AMAZON_EASY_SHIP`, `AMAZON_HAUL`, `DELIVERY_BY_AMAZON`, `FBM_SHIP_PLUS`, `IN_STORE_PICK_UP`, `PREMIUM`, `PREORDER`, `PRIME`
     */
    public function setPrograms(?array $programs): self
    {
        if (is_null($programs)) {
            array_push($this->openAPINullablesSetToNull, 'programs');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('programs', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['programs'] = $programs;

        return $this;
    }

    /**
     * Gets associated_orders.
     */
    public function getAssociatedOrders(): ?array
    {
        return $this->container['associated_orders'];
    }

    /**
     * Sets associated_orders.
     *
     * @param null|array $associated_orders other orders that have a direct relationship to this order, such as replacement or exchange orders
     */
    public function setAssociatedOrders(?array $associated_orders): self
    {
        if (is_null($associated_orders)) {
            array_push($this->openAPINullablesSetToNull, 'associated_orders');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('associated_orders', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['associated_orders'] = $associated_orders;

        return $this;
    }

    /**
     * Gets sales_channel.
     */
    public function getSalesChannel(): SalesChannel
    {
        return $this->container['sales_channel'];
    }

    /**
     * Sets sales_channel.
     *
     * @param SalesChannel $sales_channel sales_channel
     */
    public function setSalesChannel(SalesChannel $sales_channel): self
    {
        if (is_null($sales_channel)) {
            throw new \InvalidArgumentException('non-nullable sales_channel cannot be null');
        }
        $this->container['sales_channel'] = $sales_channel;

        return $this;
    }

    /**
     * Gets buyer.
     */
    public function getBuyer(): ?Buyer
    {
        return $this->container['buyer'];
    }

    /**
     * Sets buyer.
     *
     * @param null|Buyer $buyer buyer
     */
    public function setBuyer(?Buyer $buyer): self
    {
        if (is_null($buyer)) {
            array_push($this->openAPINullablesSetToNull, 'buyer');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('buyer', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['buyer'] = $buyer;

        return $this;
    }

    /**
     * Gets recipient.
     */
    public function getRecipient(): ?Recipient
    {
        return $this->container['recipient'];
    }

    /**
     * Sets recipient.
     *
     * @param null|Recipient $recipient recipient
     */
    public function setRecipient(?Recipient $recipient): self
    {
        if (is_null($recipient)) {
            array_push($this->openAPINullablesSetToNull, 'recipient');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('recipient', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['recipient'] = $recipient;

        return $this;
    }

    /**
     * Gets proceeds.
     */
    public function getProceeds(): ?OrderProceeds
    {
        return $this->container['proceeds'];
    }

    /**
     * Sets proceeds.
     *
     * @param null|OrderProceeds $proceeds proceeds
     */
    public function setProceeds(?OrderProceeds $proceeds): self
    {
        if (is_null($proceeds)) {
            array_push($this->openAPINullablesSetToNull, 'proceeds');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('proceeds', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['proceeds'] = $proceeds;

        return $this;
    }

    /**
     * Gets fulfillment.
     */
    public function getFulfillment(): ?OrderFulfillment
    {
        return $this->container['fulfillment'];
    }

    /**
     * Sets fulfillment.
     *
     * @param null|OrderFulfillment $fulfillment fulfillment
     */
    public function setFulfillment(?OrderFulfillment $fulfillment): self
    {
        if (is_null($fulfillment)) {
            array_push($this->openAPINullablesSetToNull, 'fulfillment');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fulfillment', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fulfillment'] = $fulfillment;

        return $this;
    }

    /**
     * Gets order_items.
     */
    public function getOrderItems(): array
    {
        return $this->container['order_items'];
    }

    /**
     * Sets order_items.
     *
     * @param array $order_items the list of all order items included in this order
     */
    public function setOrderItems(array $order_items): self
    {
        if (is_null($order_items)) {
            throw new \InvalidArgumentException('non-nullable order_items cannot be null');
        }
        $this->container['order_items'] = $order_items;

        return $this;
    }

    /**
     * Gets packages.
     */
    public function getPackages(): ?array
    {
        return $this->container['packages'];
    }

    /**
     * Sets packages.
     *
     * @param null|array $packages Shipping packages created for this order, including tracking information. **Note:** Only available for merchant-fulfilled (FBM) orders.
     */
    public function setPackages(?array $packages): self
    {
        if (is_null($packages)) {
            array_push($this->openAPINullablesSetToNull, 'packages');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('packages', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['packages'] = $packages;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return null|mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param null|int $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets a header-safe presentation of the object.
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of nullable properties.
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @param mixed $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }
}
