<?php

/**
 * ReplenishmentOrder.
 *
 * PHP version 8.3
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Amazon Warehousing and Distribution.
 *
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * The version of the OpenAPI document: 2024-05-09
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SpApi\Model\awd\v2024_05_09;

use SpApi\Model\ModelInterface;
use SpApi\ObjectSerializer;

/**
 * ReplenishmentOrder Class Doc Comment.
 *
 * @category Class
 *
 * @description Represents an AWD replenishment order.
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class ReplenishmentOrder implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     */
    protected static string $openAPIModelName = 'ReplenishmentOrder';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static array $openAPITypes = [
        'confirmed_on' => '\DateTime',
        'created_at' => '\DateTime',
        'distribution_ineligible_reasons' => '\SpApi\Model\awd\v2024_05_09\DistributionIneligibleReason[]',
        'eligible_products' => '\SpApi\Model\awd\v2024_05_09\DistributionProduct[]',
        'order_id' => 'string',
        'status' => '\SpApi\Model\awd\v2024_05_09\ReplenishmentOrderStatus',
        'outbound_shipments' => '\SpApi\Model\awd\v2024_05_09\OutboundShipmentSummary[]',
        'products' => '\SpApi\Model\awd\v2024_05_09\DistributionProduct[]',
        'shipped_products' => '\SpApi\Model\awd\v2024_05_09\DistributionProduct[]',
        'updated_at' => '\DateTime'];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'confirmed_on' => 'date-time',
        'created_at' => 'date-time',
        'distribution_ineligible_reasons' => null,
        'eligible_products' => null,
        'order_id' => null,
        'status' => null,
        'outbound_shipments' => null,
        'products' => null,
        'shipped_products' => null,
        'updated_at' => 'date-time'];

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'confirmed_on' => true,
        'created_at' => true,
        'distribution_ineligible_reasons' => true,
        'eligible_products' => true,
        'order_id' => false,
        'status' => false,
        'outbound_shipments' => false,
        'products' => true,
        'shipped_products' => true,
        'updated_at' => true,
    ];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'confirmed_on' => 'confirmedOn',
        'created_at' => 'createdAt',
        'distribution_ineligible_reasons' => 'distributionIneligibleReasons',
        'eligible_products' => 'eligibleProducts',
        'order_id' => 'orderId',
        'status' => 'status',
        'outbound_shipments' => 'outboundShipments',
        'products' => 'products',
        'shipped_products' => 'shippedProducts',
        'updated_at' => 'updatedAt',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static array $setters = [
        'confirmed_on' => 'setConfirmedOn',
        'created_at' => 'setCreatedAt',
        'distribution_ineligible_reasons' => 'setDistributionIneligibleReasons',
        'eligible_products' => 'setEligibleProducts',
        'order_id' => 'setOrderId',
        'status' => 'setStatus',
        'outbound_shipments' => 'setOutboundShipments',
        'products' => 'setProducts',
        'shipped_products' => 'setShippedProducts',
        'updated_at' => 'setUpdatedAt',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static array $getters = [
        'confirmed_on' => 'getConfirmedOn',
        'created_at' => 'getCreatedAt',
        'distribution_ineligible_reasons' => 'getDistributionIneligibleReasons',
        'eligible_products' => 'getEligibleProducts',
        'order_id' => 'getOrderId',
        'status' => 'getStatus',
        'outbound_shipments' => 'getOutboundShipments',
        'products' => 'getProducts',
        'shipped_products' => 'getShippedProducts',
        'updated_at' => 'getUpdatedAt',
    ];

    /**
     * Associative array for storing property values.
     */
    protected array $container = [];

    /**
     * Constructor.
     *
     * @param null|array $data Associated array of property values
     *                         initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('confirmed_on', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('distribution_ineligible_reasons', $data ?? [], null);
        $this->setIfExists('eligible_products', $data ?? [], null);
        $this->setIfExists('order_id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('outbound_shipments', $data ?? [], null);
        $this->setIfExists('products', $data ?? [], null);
        $this->setIfExists('shipped_products', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Checks if a property is nullable.
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (null === $this->container['order_id']) {
            $invalidProperties[] = "'order_id' can't be null";
        }
        if (null === $this->container['status']) {
            $invalidProperties[] = "'status' can't be null";
        }
        if (null === $this->container['outbound_shipments']) {
            $invalidProperties[] = "'outbound_shipments' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets confirmed_on.
     */
    public function getConfirmedOn(): ?\DateTime
    {
        return $this->container['confirmed_on'];
    }

    /**
     * Sets confirmed_on.
     *
     * @param null|\DateTime $confirmed_on date on which this replenishment order was confirmed
     */
    public function setConfirmedOn(?\DateTime $confirmed_on): self
    {
        if (is_null($confirmed_on)) {
            array_push($this->openAPINullablesSetToNull, 'confirmed_on');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('confirmed_on', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['confirmed_on'] = $confirmed_on;

        return $this;
    }

    /**
     * Gets created_at.
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at.
     *
     * @param null|\DateTime $created_at date on which this replenishment order was created
     */
    public function setCreatedAt(?\DateTime $created_at): self
    {
        if (is_null($created_at)) {
            array_push($this->openAPINullablesSetToNull, 'created_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('created_at', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets distribution_ineligible_reasons.
     */
    public function getDistributionIneligibleReasons(): ?array
    {
        return $this->container['distribution_ineligible_reasons'];
    }

    /**
     * Sets distribution_ineligible_reasons.
     *
     * @param null|array $distribution_ineligible_reasons Distribution errors associated with the order related to the products or packages to replenish. This field will be populated if the order has products or packages which failed validation.
     */
    public function setDistributionIneligibleReasons(?array $distribution_ineligible_reasons): self
    {
        if (is_null($distribution_ineligible_reasons)) {
            array_push($this->openAPINullablesSetToNull, 'distribution_ineligible_reasons');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('distribution_ineligible_reasons', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['distribution_ineligible_reasons'] = $distribution_ineligible_reasons;

        return $this;
    }

    /**
     * Gets eligible_products.
     */
    public function getEligibleProducts(): ?array
    {
        return $this->container['eligible_products'];
    }

    /**
     * Sets eligible_products.
     *
     * @param null|array $eligible_products list of product units that are eligible for replenishment
     */
    public function setEligibleProducts(?array $eligible_products): self
    {
        if (is_null($eligible_products)) {
            array_push($this->openAPINullablesSetToNull, 'eligible_products');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('eligible_products', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['eligible_products'] = $eligible_products;

        return $this;
    }

    /**
     * Gets order_id.
     */
    public function getOrderId(): string
    {
        return $this->container['order_id'];
    }

    /**
     * Sets order_id.
     *
     * @param string $order_id order Id of the replenishment order
     */
    public function setOrderId(string $order_id): self
    {
        if (is_null($order_id)) {
            throw new \InvalidArgumentException('non-nullable order_id cannot be null');
        }
        $this->container['order_id'] = $order_id;

        return $this;
    }

    /**
     * Gets status.
     */
    public function getStatus(): string
    {
        return $this->container['status'];
    }

    /**
     * Sets status.
     *
     * @param string $status status
     */
    public function setStatus(string $status): self
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets outbound_shipments.
     */
    public function getOutboundShipments(): array
    {
        return $this->container['outbound_shipments'];
    }

    /**
     * Sets outbound_shipments.
     *
     * @param array $outbound_shipments list of outbound shipments that are part of this order
     */
    public function setOutboundShipments(array $outbound_shipments): self
    {
        if (is_null($outbound_shipments)) {
            throw new \InvalidArgumentException('non-nullable outbound_shipments cannot be null');
        }
        $this->container['outbound_shipments'] = $outbound_shipments;

        return $this;
    }

    /**
     * Gets products.
     */
    public function getProducts(): ?array
    {
        return $this->container['products'];
    }

    /**
     * Sets products.
     *
     * @param null|array $products requested amount of single product units to be replenished
     */
    public function setProducts(?array $products): self
    {
        if (is_null($products)) {
            array_push($this->openAPINullablesSetToNull, 'products');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('products', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['products'] = $products;

        return $this;
    }

    /**
     * Gets shipped_products.
     */
    public function getShippedProducts(): ?array
    {
        return $this->container['shipped_products'];
    }

    /**
     * Sets shipped_products.
     *
     * @param null|array $shipped_products outbound product units that are shipped after the execution has completed post confirmation
     */
    public function setShippedProducts(?array $shipped_products): self
    {
        if (is_null($shipped_products)) {
            array_push($this->openAPINullablesSetToNull, 'shipped_products');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shipped_products', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['shipped_products'] = $shipped_products;

        return $this;
    }

    /**
     * Gets updated_at.
     */
    public function getUpdatedAt(): ?\DateTime
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at.
     *
     * @param null|\DateTime $updated_at date on which this replenishment order was last updated
     */
    public function setUpdatedAt(?\DateTime $updated_at): self
    {
        if (is_null($updated_at)) {
            array_push($this->openAPINullablesSetToNull, 'updated_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('updated_at', $nullablesSetToNull);
            if (false !== $index) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return null|mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param null|int $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets a header-safe presentation of the object.
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of nullable properties.
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @param mixed $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }
}
