<?php

/**
 * PackageSubStatus.
 *
 * PHP version 8.3
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Amazon External Fulfillment Shipments Processing.
 *
 * You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.
 *
 * The version of the OpenAPI document: 2024-09-11
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SpApi\Model\externalFulfillment\shipments\v2024_09_11;

/**
 * PackageSubStatus Class Doc Comment.
 *
 * @category Class
 *
 * @description The sub-status of a package.
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
class PackageSubStatus
{
    /**
     * Possible values of this enum.
     */
    public const OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY';

    public const DELIVERED = 'DELIVERED';

    public const NOT_DELIVERED = 'NOT_DELIVERED';

    public const UNDELIVERABLE = 'UNDELIVERABLE';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues(): array
    {
        return [
            self::OUT_FOR_DELIVERY,
            self::DELIVERED,
            self::NOT_DELIVERED,
            self::UNDELIVERABLE,
        ];
    }
}
