<?php
/**
 * DeliveryService
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  GeekSeller\SellingPartnerAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a merchant fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2025-09-24
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SpApi\Model\fulfillment\outbound\v2025_09_24;

use \ArrayAccess;
use \SpApi\ObjectSerializer;

/**
 * DeliveryService Class Doc Comment
 *
 * @category Class
 * @description Specify delivery settings.
 * @package  GeekSeller\SellingPartnerAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DeliveryService implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DeliveryService';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'deliver_together' => 'string',
        'signature_on_delivery' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'deliver_together' => null,
        'signature_on_delivery' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'deliver_together' => false,
		'signature_on_delivery' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'deliver_together' => 'deliverTogether',
        'signature_on_delivery' => 'signatureOnDelivery'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'deliver_together' => 'setDeliverTogether',
        'signature_on_delivery' => 'setSignatureOnDelivery'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'deliver_together' => 'getDeliverTogether',
        'signature_on_delivery' => 'getSignatureOnDelivery'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const DELIVER_TOGETHER_REQUIRED = 'REQUIRED';
    public const DELIVER_TOGETHER_NOT_REQUIRED = 'NOT_REQUIRED';
    public const SIGNATURE_ON_DELIVERY_ADULT_REQUIRED = 'ADULT_REQUIRED';
    public const SIGNATURE_ON_DELIVERY_REQUIRED = 'REQUIRED';
    public const SIGNATURE_ON_DELIVERY_NOT_REQUIRED = 'NOT_REQUIRED';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDeliverTogetherAllowableValues()
    {
        return [
            self::DELIVER_TOGETHER_REQUIRED,
            self::DELIVER_TOGETHER_NOT_REQUIRED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSignatureOnDeliveryAllowableValues()
    {
        return [
            self::SIGNATURE_ON_DELIVERY_ADULT_REQUIRED,
            self::SIGNATURE_ON_DELIVERY_REQUIRED,
            self::SIGNATURE_ON_DELIVERY_NOT_REQUIRED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('deliver_together', $data ?? [], null);
        $this->setIfExists('signature_on_delivery', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getDeliverTogetherAllowableValues();
        if (!is_null($this->container['deliver_together']) && !in_array($this->container['deliver_together'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'deliver_together', must be one of '%s'",
                $this->container['deliver_together'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSignatureOnDeliveryAllowableValues();
        if (!is_null($this->container['signature_on_delivery']) && !in_array($this->container['signature_on_delivery'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'signature_on_delivery', must be one of '%s'",
                $this->container['signature_on_delivery'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets deliver_together
     *
     * @return string|null
     */
    public function getDeliverTogether()
    {
        return $this->container['deliver_together'];
    }

    /**
     * Sets deliver_together
     *
     * @param string|null $deliver_together Whether items should be delivered together. Possible values: REQUIRED, NOT_REQUIRED.
     *
     * @return self
     */
    public function setDeliverTogether($deliver_together)
    {
        if (is_null($deliver_together)) {
            throw new \InvalidArgumentException('non-nullable deliver_together cannot be null');
        }
        $allowedValues = $this->getDeliverTogetherAllowableValues();
        if (!in_array($deliver_together, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'deliver_together', must be one of '%s'",
                    $deliver_together,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['deliver_together'] = $deliver_together;

        return $this;
    }

    /**
     * Gets signature_on_delivery
     *
     * @return string|null
     */
    public function getSignatureOnDelivery()
    {
        return $this->container['signature_on_delivery'];
    }

    /**
     * Sets signature_on_delivery
     *
     * @param string|null $signature_on_delivery The signature requirement for delivery. Possible values: ADULT_REQUIRED, REQUIRED, NOT_REQUIRED.
     *
     * @return self
     */
    public function setSignatureOnDelivery($signature_on_delivery)
    {
        if (is_null($signature_on_delivery)) {
            throw new \InvalidArgumentException('non-nullable signature_on_delivery cannot be null');
        }
        $allowedValues = $this->getSignatureOnDeliveryAllowableValues();
        if (!in_array($signature_on_delivery, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'signature_on_delivery', must be one of '%s'",
                    $signature_on_delivery,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['signature_on_delivery'] = $signature_on_delivery;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


