<?php
/**
 * GetOrderPreviewRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  GeekSeller\SellingPartnerAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a merchant fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2025-09-24
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SpApi\Model\fulfillment\outbound\v2025_09_24;

use \ArrayAccess;
use \SpApi\ObjectSerializer;

/**
 * GetOrderPreviewRequest Class Doc Comment
 *
 * @category Class
 * @description The request body schema for the GetOrderPreview operation.
 * @package  GeekSeller\SellingPartnerAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetOrderPreviewRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetOrderPreviewRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'delivery_service_levels' => 'string[]',
        'destination' => '\SpApi\Model\fulfillment\outbound\v2025_09_24\GetOrderPreviewDestination',
        'origin' => '\SpApi\Model\fulfillment\outbound\v2025_09_24\GetOrderPreviewOrigin',
        'services' => '\SpApi\Model\fulfillment\outbound\v2025_09_24\GetOrderPreviewServices',
        'line_items' => '\SpApi\Model\fulfillment\outbound\v2025_09_24\GetOrderPreviewLineItem[]',
        'exclude_estimated_fees' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'delivery_service_levels' => null,
        'destination' => null,
        'origin' => null,
        'services' => null,
        'line_items' => null,
        'exclude_estimated_fees' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'delivery_service_levels' => false,
		'destination' => false,
		'origin' => false,
		'services' => false,
		'line_items' => false,
		'exclude_estimated_fees' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'delivery_service_levels' => 'deliveryServiceLevels',
        'destination' => 'destination',
        'origin' => 'origin',
        'services' => 'services',
        'line_items' => 'lineItems',
        'exclude_estimated_fees' => 'excludeEstimatedFees'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'delivery_service_levels' => 'setDeliveryServiceLevels',
        'destination' => 'setDestination',
        'origin' => 'setOrigin',
        'services' => 'setServices',
        'line_items' => 'setLineItems',
        'exclude_estimated_fees' => 'setExcludeEstimatedFees'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'delivery_service_levels' => 'getDeliveryServiceLevels',
        'destination' => 'getDestination',
        'origin' => 'getOrigin',
        'services' => 'getServices',
        'line_items' => 'getLineItems',
        'exclude_estimated_fees' => 'getExcludeEstimatedFees'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('delivery_service_levels', $data ?? [], null);
        $this->setIfExists('destination', $data ?? [], null);
        $this->setIfExists('origin', $data ?? [], null);
        $this->setIfExists('services', $data ?? [], null);
        $this->setIfExists('line_items', $data ?? [], null);
        $this->setIfExists('exclude_estimated_fees', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['destination'] === null) {
            $invalidProperties[] = "'destination' can't be null";
        }
        if ($this->container['line_items'] === null) {
            $invalidProperties[] = "'line_items' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets delivery_service_levels
     *
     * @return string[]|null
     */
    public function getDeliveryServiceLevels()
    {
        return $this->container['delivery_service_levels'];
    }

    /**
     * Sets delivery_service_levels
     *
     * @param string[]|null $delivery_service_levels A list of delivery speeds to request fulfillment preview information for. Possible values: STANDARD, EXPEDITED, PRIORITY, SCHEDULED.
     *
     * @return self
     */
    public function setDeliveryServiceLevels($delivery_service_levels)
    {
        if (is_null($delivery_service_levels)) {
            throw new \InvalidArgumentException('non-nullable delivery_service_levels cannot be null');
        }
        $this->container['delivery_service_levels'] = $delivery_service_levels;

        return $this;
    }

    /**
     * Gets destination
     *
     * @return \SpApi\Model\fulfillment\outbound\v2025_09_24\GetOrderPreviewDestination
     */
    public function getDestination()
    {
        return $this->container['destination'];
    }

    /**
     * Sets destination
     *
     * @param \SpApi\Model\fulfillment\outbound\v2025_09_24\GetOrderPreviewDestination $destination destination
     *
     * @return self
     */
    public function setDestination($destination)
    {
        if (is_null($destination)) {
            throw new \InvalidArgumentException('non-nullable destination cannot be null');
        }
        $this->container['destination'] = $destination;

        return $this;
    }

    /**
     * Gets origin
     *
     * @return \SpApi\Model\fulfillment\outbound\v2025_09_24\GetOrderPreviewOrigin|null
     */
    public function getOrigin()
    {
        return $this->container['origin'];
    }

    /**
     * Sets origin
     *
     * @param \SpApi\Model\fulfillment\outbound\v2025_09_24\GetOrderPreviewOrigin|null $origin origin
     *
     * @return self
     */
    public function setOrigin($origin)
    {
        if (is_null($origin)) {
            throw new \InvalidArgumentException('non-nullable origin cannot be null');
        }
        $this->container['origin'] = $origin;

        return $this;
    }

    /**
     * Gets services
     *
     * @return \SpApi\Model\fulfillment\outbound\v2025_09_24\GetOrderPreviewServices|null
     */
    public function getServices()
    {
        return $this->container['services'];
    }

    /**
     * Sets services
     *
     * @param \SpApi\Model\fulfillment\outbound\v2025_09_24\GetOrderPreviewServices|null $services services
     *
     * @return self
     */
    public function setServices($services)
    {
        if (is_null($services)) {
            throw new \InvalidArgumentException('non-nullable services cannot be null');
        }
        $this->container['services'] = $services;

        return $this;
    }

    /**
     * Gets line_items
     *
     * @return \SpApi\Model\fulfillment\outbound\v2025_09_24\GetOrderPreviewLineItem[]
     */
    public function getLineItems()
    {
        return $this->container['line_items'];
    }

    /**
     * Sets line_items
     *
     * @param \SpApi\Model\fulfillment\outbound\v2025_09_24\GetOrderPreviewLineItem[] $line_items A list of items to include in the fulfillment preview, including quantity.
     *
     * @return self
     */
    public function setLineItems($line_items)
    {
        if (is_null($line_items)) {
            throw new \InvalidArgumentException('non-nullable line_items cannot be null');
        }
        $this->container['line_items'] = $line_items;

        return $this;
    }

    /**
     * Gets exclude_estimated_fees
     *
     * @return bool|null
     */
    public function getExcludeEstimatedFees()
    {
        return $this->container['exclude_estimated_fees'];
    }

    /**
     * Sets exclude_estimated_fees
     *
     * @param bool|null $exclude_estimated_fees When true, excludes estimated fees from the preview response for latency optimization. When false or not provided, includes rich data with estimated fees. Default: false.
     *
     * @return self
     */
    public function setExcludeEstimatedFees($exclude_estimated_fees)
    {
        if (is_null($exclude_estimated_fees)) {
            throw new \InvalidArgumentException('non-nullable exclude_estimated_fees cannot be null');
        }
        $this->container['exclude_estimated_fees'] = $exclude_estimated_fees;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


