<?php
/**
 * GetOrderApiTest
 * PHP version 8.3
 *
 * @category Class
 * @package  SpApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Selling Partner API for Orders
 *
 * The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SpApi\Test\Api;

use SpApi\ApiException;
use SpApi\Api\orders\v2026_01_01\GetOrderApi;
use SpApi\ObjectSerializer;

/**
 * GetOrderApiTest Class Doc Comment
 *
 * @category Class
 * @package  SpApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GetOrderApiTest extends BaseTestCase
{
    private GetOrderApi $apiInstance;
    public function setUp(): void
    {
        parent::setUp();
        // Initialize parameter value specific to case
        $this->testHelper->setSpecificValue('GetOrderApi', $this->getName());
        $this->apiInstance = new GetOrderApi($this->config, null);
        // Change Time Format if it requires
        $specificTimeFormat = $this->testHelper->getDateTimeFormatForCase('GetOrderApi');
        if ($specificTimeFormat) {
            ObjectSerializer::setDateTimeFormat($specificTimeFormat);
        }
    }

    /**
     * Test case for getOrder_200
     */
    public function testGetOrder200()
    {
        try {
            // Skip test if it is in the skip list
            if ($this->testHelper->shouldSkipTest('testGetOrder200', 'GetOrderApi')) {
                $this->assertTrue(true);
                return;
            }
            $jsonSchema = '{
  &quot;description&quot; : &quot;Success.&quot;,
  &quot;headers&quot; : {
    &quot;x-amzn-RequestId&quot; : {
      &quot;description&quot; : &quot;Unique request reference identifier.&quot;,
      &quot;schema&quot; : {
        &quot;type&quot; : &quot;string&quot;
      }
    },
    &quot;x-amzn-RateLimit-Limit&quot; : {
      &quot;description&quot; : &quot;Your rate limit (requests per second) for this operation.&quot;,
      &quot;schema&quot; : {
        &quot;type&quot; : &quot;string&quot;
      }
    }
  },
  &quot;content&quot; : {
    &quot;application/json&quot; : {
      &quot;schema&quot; : {
        &quot;$ref&quot; : &quot;#/components/schemas/GetOrderResponse&quot;
      },
      &quot;example&quot; : {
        &quot;order&quot; : {
          &quot;orderId&quot; : &quot;202-1234567-8901234&quot;,
          &quot;orderAliases&quot; : [ {
            &quot;aliasId&quot; : &quot;UK-MERCHANT-ORDER-2024-001&quot;,
            &quot;aliasType&quot; : &quot;SELLER_ORDER_ID&quot;
          } ],
          &quot;createdTime&quot; : &quot;2024-12-25T09:15:00Z&quot;,
          &quot;lastUpdatedTime&quot; : &quot;2024-12-25T16:30:00Z&quot;,
          &quot;programs&quot; : [ &quot;PRIME&quot; ],
          &quot;salesChannel&quot; : {
            &quot;channelName&quot; : &quot;AMAZON&quot;,
            &quot;marketplaceId&quot; : &quot;A1F83G8C2ARO7P&quot;,
            &quot;marketplaceName&quot; : &quot;Amazon.co.uk&quot;
          },
          &quot;buyer&quot; : {
            &quot;buyerName&quot; : &quot;James Wilson&quot;,
            &quot;buyerEmail&quot; : &quot;buyer-email@marketplace.amazon.co.uk&quot;
          },
          &quot;recipient&quot; : {
            &quot;deliveryAddress&quot; : {
              &quot;name&quot; : &quot;James Wilson&quot;,
              &quot;companyName&quot; : &quot;Wilson Electronics Ltd&quot;,
              &quot;addressLine1&quot; : &quot;123 High Street&quot;,
              &quot;addressLine2&quot; : &quot;Unit 4B&quot;,
              &quot;addressLine3&quot; : &quot;&quot;,
              &quot;city&quot; : &quot;Manchester&quot;,
              &quot;districtOrCounty&quot; : &quot;Greater Manchester&quot;,
              &quot;stateOrRegion&quot; : &quot;England&quot;,
              &quot;municipality&quot; : &quot;&quot;,
              &quot;postalCode&quot; : &quot;M1 2AB&quot;,
              &quot;countryCode&quot; : &quot;GB&quot;,
              &quot;phone&quot; : &quot;+44 161 123 4567&quot;,
              &quot;addressType&quot; : &quot;COMMERCIAL&quot;
            }
          },
          &quot;proceeds&quot; : {
            &quot;grandTotal&quot; : {
              &quot;amount&quot; : &quot;103.97&quot;,
              &quot;currencyCode&quot; : &quot;GBP&quot;
            }
          },
          &quot;fulfillment&quot; : {
            &quot;fulfillmentStatus&quot; : &quot;SHIPPED&quot;,
            &quot;fulfilledBy&quot; : &quot;MERCHANT&quot;,
            &quot;fulfillmentServiceLevel&quot; : &quot;STANDARD&quot;,
            &quot;shipByWindow&quot; : {
              &quot;earliestDateTime&quot; : &quot;2024-12-25T00:00:00Z&quot;,
              &quot;latestDateTime&quot; : &quot;2024-12-26T23:59:59Z&quot;
            },
            &quot;deliverByWindow&quot; : {
              &quot;earliestDateTime&quot; : &quot;2024-12-27T00:00:00Z&quot;,
              &quot;latestDateTime&quot; : &quot;2024-12-30T23:59:59Z&quot;
            }
          },
          &quot;orderItems&quot; : [ {
            &quot;orderItemId&quot; : &quot;20212345678901&quot;,
            &quot;quantityOrdered&quot; : 3,
            &quot;programs&quot; : [ &quot;TRANSPARENCY&quot; ],
            &quot;product&quot; : {
              &quot;asin&quot; : &quot;B08DFPV54V&quot;,
              &quot;title&quot; : &quot;Echo Dot (4th Gen) | Smart speaker with Alexa | Charcoal&quot;,
              &quot;sellerSku&quot; : &quot;ECHO-DOT-4-UK-CHARCOAL-3PACK&quot;,
              &quot;condition&quot; : {
                &quot;conditionType&quot; : &quot;NEW&quot;,
                &quot;conditionSubtype&quot; : &quot;NEW&quot;,
                &quot;conditionNote&quot; : &quot;Brand new, sealed in original packaging&quot;
              },
              &quot;price&quot; : {
                &quot;unitPrice&quot; : {
                  &quot;amount&quot; : &quot;29.99&quot;,
                  &quot;currencyCode&quot; : &quot;GBP&quot;
                },
                &quot;priceDesignation&quot; : &quot;BUSINESS_PRICE&quot;
              },
              &quot;serialNumbers&quot; : [ &quot;ED4UK-2024-ABC123456789&quot;, &quot;ED4UK-2024-DEF987654321&quot;, &quot;ED4UK-2024-GHI456789123&quot; ],
              &quot;customization&quot; : {
                &quot;customizedUrl&quot; : &quot;&quot;
              }
            },
            &quot;proceeds&quot; : {
              &quot;proceedsTotal&quot; : {
                &quot;amount&quot; : &quot;103.97&quot;,
                &quot;currencyCode&quot; : &quot;GBP&quot;
              },
              &quot;breakdowns&quot; : [ {
                &quot;type&quot; : &quot;ITEM&quot;,
                &quot;subtotal&quot; : {
                  &quot;amount&quot; : &quot;89.97&quot;,
                  &quot;currencyCode&quot; : &quot;GBP&quot;
                }
              }, {
                &quot;type&quot; : &quot;SHIPPING&quot;,
                &quot;subtotal&quot; : {
                  &quot;amount&quot; : &quot;10.00&quot;,
                  &quot;currencyCode&quot; : &quot;GBP&quot;
                }
              }, {
                &quot;type&quot; : &quot;TAX&quot;,
                &quot;subtotal&quot; : {
                  &quot;amount&quot; : &quot;4.00&quot;,
                  &quot;currencyCode&quot; : &quot;GBP&quot;
                },
                &quot;detailedBreakdowns&quot; : [ {
                  &quot;subtype&quot; : &quot;ITEM&quot;,
                  &quot;value&quot; : {
                    &quot;amount&quot; : &quot;3.00&quot;,
                    &quot;currencyCode&quot; : &quot;GBP&quot;
                  }
                }, {
                  &quot;subtype&quot; : &quot;SHIPPING&quot;,
                  &quot;value&quot; : {
                    &quot;amount&quot; : &quot;1.00&quot;,
                    &quot;currencyCode&quot; : &quot;GBP&quot;
                  }
                } ]
              } ]
            },
            &quot;promotion&quot; : {
              &quot;breakdowns&quot; : [ {
                &quot;promotionId&quot; : &quot;UK-BOXING-DAY-2024&quot;
              } ]
            },
            &quot;fulfillment&quot; : {
              &quot;quantityFulfilled&quot; : 3,
              &quot;quantityUnfulfilled&quot; : 0,
              &quot;packing&quot; : {
                &quot;giftOption&quot; : {
                  &quot;giftMessage&quot; : &quot;Happy Christmas! Hope you enjoy your new smart speakers.&quot;,
                  &quot;giftWrapLevel&quot; : &quot;PREMIUM&quot;
                }
              },
              &quot;shipping&quot; : {
                &quot;scheduledDeliveryWindow&quot; : {
                  &quot;earliestDateTime&quot; : &quot;2024-12-27T09:00:00Z&quot;,
                  &quot;latestDateTime&quot; : &quot;2024-12-27T17:00:00Z&quot;
                },
                &quot;shippingConstraints&quot; : {
                  &quot;signatureConfirmation&quot; : &quot;MANDATORY&quot;,
                  &quot;recipientIdentityVerification&quot; : &quot;MANDATORY&quot;
                },
                &quot;internationalShipping&quot; : {
                  &quot;iossNumber&quot; : &quot;IM1234567890&quot;
                }
              }
            }
          } ],
          &quot;packages&quot; : [ {
            &quot;packageReferenceId&quot; : &quot;UK-PKG-2024-001&quot;,
            &quot;createdTime&quot; : &quot;2024-12-25T16:45:00Z&quot;,
            &quot;packageStatus&quot; : {
              &quot;status&quot; : &quot;IN_TRANSIT&quot;,
              &quot;detailedStatus&quot; : &quot;OUT_FOR_DELIVERY&quot;
            },
            &quot;carrier&quot; : &quot;Royal Mail&quot;,
            &quot;shipTime&quot; : &quot;2024-12-26T14:00:00Z&quot;,
            &quot;shippingService&quot; : &quot;Royal Mail Tracked 48&quot;,
            &quot;trackingNumber&quot; : &quot;RR123456789GB&quot;,
            &quot;shipFromAddress&quot; : {
              &quot;name&quot; : &quot;TechGear UK Warehouse&quot;,
              &quot;addressLine1&quot; : &quot;Industrial Estate Unit 15&quot;,
              &quot;addressLine2&quot; : &quot;Riverside Business Park&quot;,
              &quot;addressLine3&quot; : &quot;&quot;,
              &quot;city&quot; : &quot;Birmingham&quot;,
              &quot;districtOrCounty&quot; : &quot;West Midlands&quot;,
              &quot;stateOrRegion&quot; : &quot;England&quot;,
              &quot;municipality&quot; : &quot;&quot;,
              &quot;postalCode&quot; : &quot;B12 0XY&quot;,
              &quot;countryCode&quot; : &quot;GB&quot;
            },
            &quot;packageItems&quot; : [ {
              &quot;orderItemId&quot; : &quot;20212345678901&quot;,
              &quot;quantity&quot; : 3,
              &quot;transparencyCodes&quot; : [ &quot;T12345ABCDE67890UK&quot;, &quot;T12346ABCDF67891UK&quot;, &quot;T12347ABCDG67892UK&quot; ]
            } ]
          } ]
        }
      }
    }
  },
  &quot;x-amzn-api-sandbox&quot; : {
    &quot;static&quot; : [ {
      &quot;request&quot; : {
        &quot;parameters&quot; : {
          &quot;orderId&quot; : {
            &quot;value&quot; : &quot;171-9876543-2109876&quot;
          },
          &quot;includedData&quot; : {
            &quot;value&quot; : [ &quot;BUYER&quot;, &quot;RECIPIENT&quot;, &quot;PROCEEDS&quot;, &quot;EXPENSE&quot;, &quot;PROMOTION&quot;, &quot;CANCELLATION&quot;, &quot;FULFILLMENT&quot;, &quot;PACKAGES&quot; ]
          }
        }
      },
      &quot;response&quot; : {
        &quot;order&quot; : {
          &quot;orderId&quot; : &quot;171-9876543-2109876&quot;,
          &quot;orderAliases&quot; : [ {
            &quot;aliasId&quot; : &quot;BR-CONSUMER-ORDER-2024-003&quot;,
            &quot;aliasType&quot; : &quot;SELLER_ORDER_ID&quot;
          } ],
          &quot;createdTime&quot; : &quot;2024-12-24T20:30:00Z&quot;,
          &quot;lastUpdatedTime&quot; : &quot;2024-12-25T08:15:00Z&quot;,
          &quot;programs&quot; : [ &quot;PRIME&quot; ],
          &quot;salesChannel&quot; : {
            &quot;channelName&quot; : &quot;AMAZON&quot;,
            &quot;marketplaceId&quot; : &quot;A2Q3Y263D00KWC&quot;,
            &quot;marketplaceName&quot; : &quot;Amazon.com.br&quot;
          },
          &quot;buyer&quot; : {
            &quot;buyerName&quot; : &quot;Maria Silva Santos&quot;,
            &quot;buyerEmail&quot; : &quot;buyer-email@marketplace.amazon.com.br&quot;
          },
          &quot;recipient&quot; : {
            &quot;deliveryAddress&quot; : {
              &quot;name&quot; : &quot;Maria Silva Santos&quot;,
              &quot;addressLine1&quot; : &quot;Rua das Flores, 123&quot;,
              &quot;addressLine2&quot; : &quot;Apartamento 45&quot;,
              &quot;addressLine3&quot; : &quot;&quot;,
              &quot;city&quot; : &quot;São Paulo&quot;,
              &quot;districtOrCounty&quot; : &quot;&quot;,
              &quot;stateOrRegion&quot; : &quot;SP&quot;,
              &quot;municipality&quot; : &quot;&quot;,
              &quot;postalCode&quot; : &quot;01234-567&quot;,
              &quot;countryCode&quot; : &quot;BR&quot;,
              &quot;phone&quot; : &quot;+55 11 98765-4321&quot;,
              &quot;extendedFields&quot; : {
                &quot;streetName&quot; : &quot;Rua das Flores&quot;,
                &quot;streetNumber&quot; : &quot;123&quot;,
                &quot;complement&quot; : &quot;Apartamento 45&quot;,
                &quot;neighborhood&quot; : &quot;Vila Madalena&quot;
              },
              &quot;addressType&quot; : &quot;RESIDENTIAL&quot;
            }
          },
          &quot;proceeds&quot; : {
            &quot;grandTotal&quot; : {
              &quot;amount&quot; : &quot;299.90&quot;,
              &quot;currencyCode&quot; : &quot;BRL&quot;
            }
          },
          &quot;fulfillment&quot; : {
            &quot;fulfillmentStatus&quot; : &quot;UNSHIPPED&quot;,
            &quot;fulfilledBy&quot; : &quot;MERCHANT&quot;,
            &quot;fulfillmentServiceLevel&quot; : &quot;STANDARD&quot;,
            &quot;shipByWindow&quot; : {
              &quot;earliestDateTime&quot; : &quot;2024-12-26T00:00:00Z&quot;,
              &quot;latestDateTime&quot; : &quot;2024-12-27T23:59:59Z&quot;
            },
            &quot;deliverByWindow&quot; : {
              &quot;earliestDateTime&quot; : &quot;2024-12-28T00:00:00Z&quot;,
              &quot;latestDateTime&quot; : &quot;2024-12-31T23:59:59Z&quot;
            }
          },
          &quot;orderItems&quot; : [ {
            &quot;orderItemId&quot; : &quot;17198765432109&quot;,
            &quot;quantityOrdered&quot; : 1,
            &quot;product&quot; : {
              &quot;asin&quot; : &quot;B08N5WRWNW&quot;,
              &quot;title&quot; : &quot;Echo Dot (4ª Geração) | Smart Speaker com Alexa | Cor Preta&quot;,
              &quot;sellerSku&quot; : &quot;ECHO-DOT-4-BR-PRETO&quot;,
              &quot;condition&quot; : {
                &quot;conditionType&quot; : &quot;NEW&quot;,
                &quot;conditionSubtype&quot; : &quot;NEW&quot;,
                &quot;conditionNote&quot; : &quot;&quot;
              },
              &quot;price&quot; : {
                &quot;unitPrice&quot; : {
                  &quot;amount&quot; : &quot;299.90&quot;,
                  &quot;currencyCode&quot; : &quot;BRL&quot;
                }
              }
            },
            &quot;proceeds&quot; : {
              &quot;proceedsTotal&quot; : {
                &quot;amount&quot; : &quot;299.90&quot;,
                &quot;currencyCode&quot; : &quot;BRL&quot;
              },
              &quot;breakdowns&quot; : [ {
                &quot;type&quot; : &quot;ITEM&quot;,
                &quot;subtotal&quot; : {
                  &quot;amount&quot; : &quot;299.90&quot;,
                  &quot;currencyCode&quot; : &quot;BRL&quot;
                }
              } ]
            },
            &quot;promotion&quot; : {
              &quot;breakdowns&quot; : [ {
                &quot;promotionId&quot; : &quot;BR-NATAL-2024&quot;
              } ]
            },
            &quot;fulfillment&quot; : {
              &quot;quantityFulfilled&quot; : 0,
              &quot;quantityUnfulfilled&quot; : 1,
              &quot;packing&quot; : {
                &quot;giftOption&quot; : {
                  &quot;giftMessage&quot; : &quot;Feliz Natal! Espero que goste do seu novo alto-falante inteligente!&quot;,
                  &quot;giftWrapLevel&quot; : &quot;STANDARD&quot;
                }
              }
            }
          } ]
        }
      }
    } ]
  }
}';
            $result = $this->testHelper->extractRequestAndResponse(
                $this->apiInstance,
                $jsonSchema,
                'getOrder'
            );
            $requestParams = $result['requestParams'];
            $expectedResponse = $result['expectedResponse'];

            // Change Time Format if it requires
            $specificTimeFormat = $this->testHelper->getDateTimeFormatForCase('GetOrderApi');
            if ($specificTimeFormat) {
                ObjectSerializer::setDateTimeFormat($specificTimeFormat);
            }

            // Act: Call API
            list($response, $statusCode, $headers) =
                $this->apiInstance->getOrderWithHttpInfo(...array_values($requestParams));

            // Assert the response code
            $this->assertHttpStatusCode(200, $statusCode);

            // Handle different response codes
            $this->handleResponse($response, $statusCode, 200, $expectedResponse);
        } catch (ApiException $e) {
            $this->handleApiException($e, 200);
        } catch (\ReflectionException $e) {
            $this->fail("Reflection exception: " . $e->getMessage());
        }
    }
    /**
     * Test case for getOrder_400
     */
    public function testGetOrder400()
    {
        try {
            // Skip test if it is in the skip list
            if ($this->testHelper->shouldSkipTest('testGetOrder400', 'GetOrderApi')) {
                $this->assertTrue(true);
                return;
            }
            $jsonSchema = '{
  &quot;description&quot; : &quot;Request has missing or invalid parameters and cannot be parsed.&quot;,
  &quot;headers&quot; : {
    &quot;x-amzn-RequestId&quot; : {
      &quot;description&quot; : &quot;Unique request reference identifier.&quot;,
      &quot;schema&quot; : {
        &quot;type&quot; : &quot;string&quot;
      }
    },
    &quot;x-amzn-RateLimit-Limit&quot; : {
      &quot;description&quot; : &quot;Your rate limit (requests per second) for this operation.&quot;,
      &quot;schema&quot; : {
        &quot;type&quot; : &quot;string&quot;
      }
    }
  },
  &quot;content&quot; : {
    &quot;application/json&quot; : {
      &quot;schema&quot; : {
        &quot;$ref&quot; : &quot;#/components/schemas/ErrorList&quot;
      }
    }
  },
  &quot;x-amzn-api-sandbox&quot; : {
    &quot;static&quot; : [ {
      &quot;request&quot; : {
        &quot;parameters&quot; : {
          &quot;orderId&quot; : {
            &quot;value&quot; : &quot;TEST_CASE_400&quot;
          }
        }
      },
      &quot;response&quot; : {
        &quot;errors&quot; : [ {
          &quot;code&quot; : &quot;InvalidInput&quot;,
          &quot;message&quot; : &quot;Invalid Input&quot;
        } ]
      }
    } ]
  }
}';
            $result = $this->testHelper->extractRequestAndResponse(
                $this->apiInstance,
                $jsonSchema,
                'getOrder'
            );
            $requestParams = $result['requestParams'];
            $expectedResponse = $result['expectedResponse'];

            // Change Time Format if it requires
            $specificTimeFormat = $this->testHelper->getDateTimeFormatForCase('GetOrderApi');
            if ($specificTimeFormat) {
                ObjectSerializer::setDateTimeFormat($specificTimeFormat);
            }

            // Act: Call API
            list($response, $statusCode, $headers) =
                $this->apiInstance->getOrderWithHttpInfo(...array_values($requestParams));

            // Assert the response code
            $this->assertHttpStatusCode(400, $statusCode);

            // Handle different response codes
            $this->handleResponse($response, $statusCode, 400, $expectedResponse);
        } catch (ApiException $e) {
            $this->handleApiException($e, 400);
        } catch (\ReflectionException $e) {
            $this->fail("Reflection exception: " . $e->getMessage());
        }
    }
    /**
     * Test case for getOrder_403
     */
    public function testGetOrder403()
    {
        // Skip this test
        $this->markTestSkipped('Skip test for this operation.');
    }
    /**
     * Test case for getOrder_404
     */
    public function testGetOrder404()
    {
        // Skip this test
        $this->markTestSkipped('Skip test for this operation.');
    }
    /**
     * Test case for getOrder_413
     */
    public function testGetOrder413()
    {
        // Skip this test
        $this->markTestSkipped('Skip test for this operation.');
    }
    /**
     * Test case for getOrder_415
     */
    public function testGetOrder415()
    {
        // Skip this test
        $this->markTestSkipped('Skip test for this operation.');
    }
    /**
     * Test case for getOrder_429
     */
    public function testGetOrder429()
    {
        // Skip this test
        $this->markTestSkipped('Skip test for this operation.');
    }
    /**
     * Test case for getOrder_500
     */
    public function testGetOrder500()
    {
        // Skip this test
        $this->markTestSkipped('Skip test for this operation.');
    }
    /**
     * Test case for getOrder_503
     */
    public function testGetOrder503()
    {
        // Skip this test
        $this->markTestSkipped('Skip test for this operation.');
    }
}
